# Generated by Django 2.0.5 on 2018-08-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_user'),
    ]

    operations = [
    ]
